# -*- coding: utf-8 -*-
"""TDCaseStudy.ipynb

Automatically generated by Colab.


Created By: Nikhil Kothari
Date: February 12, 2026
Reason: TD Case Study
"""

import json

import pandas as pd

from google.colab import files
uploaded = files.upload()

with open("train_fraud_labels.json") as tfl:
    data = json.load(tfl)

items = data["target"].items()

df = pd.DataFrame(items, columns=["ID", "Target"])

df["ID"] = df["ID"].astype("string")
df["Target"] = df["Target"].astype("category")

df.to_csv("train_fraud_labels.csv", index=False)

from google.colab import files
files.download("train_fraud_labels.csv")

from google.colab import files
uploaded = files.upload()

with open("mcc_codes.json") as mcc:
    data_mcc = json.load(mcc)

mcc_df = pd.DataFrame(list(data_mcc.items()), columns=["MCC_Code", "MCC_Description"])

#Applying valid datatypes
mcc_df["MCC_Code"] = mcc_df["MCC_Code"].astype("string")
mcc_df["MCC_Description"] = mcc_df["MCC_Description"].astype("string")

mcc_df.head()

mcc_df.to_csv("mcc_codes.csv", index=False)

from google.colab import files
files.download("mcc_codes.csv")